platform :ios, '8.0'
target '江宁旅游局OA' do
pod 'AFNetworking','~>3.1.0'
pod 'Masonry','1.0.2'
pod 'MBProgressHUD','1.0.0'
pod 'MJRefresh','3.1.12'
pod 'SFHFKeychainUtils','0.0.1'
pod 'MJExtension','3.0.13'
pod 'SAMKeychain','1.5.2'
pod 'SDWebImage’,'4.0.0'
pod 'UICKeyChainStore’,'2.1.0'
end
